### ISSUE TITLE
Make "ci skip" configurable (as command line option)

### ISSUE THREAD

**Issue by fhuonder** [conveyal/maven-semantic-release#20]
Hi,

In _git.js_ in the method saveChangesToPomXml both commit messages (for SNAPSHOT and final versions) contain _[ci skip]_. 
We have a scenario where we run subsequent pipelines when the commit is done. With _[ci skip]_ this does not work.

Therefore I propose to introduce two new flags to the semantic-release command (like --skip-maven-deploy):

- --disable-snapshot-skip-ci
- --disable-final-skip-ci

both flags would be _false_ by default.
One could then run semantic-release like
`semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --disable-snapshot-skip-ci --disable-final-skip-ci`

If you agree I would be glad to provide a PR.

Regards,
Florian

**Comment by evansiroky** [comment]
This sounds fine to me, I look forward to seeing the PR.  :)

**Comment by evansiroky** [comment]
:tada: This issue has been resolved with version 4.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@conveyal/maven-semantic-release)
- [GitHub release](https://github.com/conveyal/maven-semantic-release/releases/tag/v4.4.0)
