### ISSUE TITLE
Conveyal workflow with @semantic/changelog plugin

### ISSUE THREAD

**Issue by pjotre86** [conveyal/maven-semantic-release#24]
Hey!
Nice plugin, thanks for sharing this!
I got it working, there's just one small piece missing:
Is there a way of successfully combining the conveyal workflow and using the changelog plugin at the same time.
I tried it, but it looks like the CHANGELOG.md is generated during the build but not being added to the commit by this plugin. So it's effectively lost.
Or do you know a different way of generating a CHANGELOG.md during the build?
Cheers!

**Comment by evansiroky** [comment]
I haven't used the changelog plugin, but could see how the Conveyal workflow would not add any other changes to other files that a user would want to add to the commit history. The way to make this work might be to add some kind of way to inject an additional file search string and then do another `git add FILE_SEARCH_STRING` in the prepare step. I'd be happy to accept a PR for this.

**Comment by pjotre86** [comment]
Cool, I'll try to find some time within the upcoming 2 weeks to create PR.
Thanks so far!
