### ISSUE TITLE
The link to generate GPG signature in readme.md is broken.

### ISSUE THREAD

**Issue by tldyl** [conveyal/maven-semantic-release#33]
![image](https://user-images.githubusercontent.com/32929029/83991949-15cf3d80-a981-11ea-9959-6f816c85b3fe.png)

**Comment by tldyl** [comment]
Do you have any good alternative now?

**Comment by evansiroky** [comment]
Bummer that the link is dead. Looks like you can still view the article via archive.org [over here](https://web.archive.org/web/20190927112225/http://www.debonair.io/post/maven-cd/#create-code-signing-cert:a547b4a31e9ae1ba41fe3873843c9208). I'll leave this issue open in case anyone else finds a better alternative article to link to.
